name: Construction de project

on:
  push:
    branches:   ["main", "develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download source
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn package --file pom.xml