name: Construction de project

on:
  push:
    branches:   ["main", "develop"]
  workflow_dispatch:


jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: create folder on remote VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: mkdir -p /opt/applications/sa
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download source
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Rename Jar
      run: mv target/*.jar target/sa.jar
    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.7
      needs: create-folder
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "target/sa.jar"
        target: /opt/applications/sa